
export const WordSearchData = [
  {
    id: 1,
    values: [
      "Psychologist",
      "Accountant",
      "Researcher",
      "Hairdresser",
      "Carpenter",
      "Academic",
      "Teacher",
      "Lawyer",
      "Athlete",
      "Gamer",
      "Chef",
      "Engineer",
      "Chemist",
      "Farmer",
      "Doctor",
    ],
  },
  {
    id: 2,
    values: [
      "Horticulturalist",
      "Epidemiologist",
      "Politician",
      "Astronomer",
      "Professor",
      "Physicist",
      "Scientist",
      "Volunteer",
      "Designer",
      "Plumber",
      "Youtuber",
      "Dietician",
      "Dentist",
      "Nurse",
      "Vet",
    ],
  },
  {
    id: 3,
    values: [
      "Businessowner",
      "Optometrist",
      "Journalist",
      "Marketing",
      "Inventor",
      "Dancer",
      "Olympian",
      "Trader",
      "Police",
      "Singer",
      "Artist",
      "Writer",
      "Army",
    ],
  },
  {
    id: 4,
    values: [
        "Accommodation",
        "Undergraduate",
        "Scholarships",
        "Postgraduate",
        "TAFE",
        "University",
        "Diploma",
        "Degree",
        "Study",
        "ATAR",
    ],
  },
  {
    id: 5,
    values: [
        "Apprenticeship",
        "Internship",
        "Secondary",
        "Education",
        "Tertiary",
        "Volunteer",
        "Learning",
        "Career",
        "Vocation",
        "Primary",
    ],
  },
  {
    id: 6,
    values: [
        "Qualification",
        "Achievement",
        "Knowledge",
        "High School",
        "Goals",
        "Occupation",
        "Training",
        "Graduate",
        "Jobs",
        "HSC",
    ],
  },
  {
    id: 7,
    values: [
        "Compassionate",
        "Intelligent",
        "Creative",
        "Curious",
        "Friendly",
        "Helpful",
        "Sporty",
        "Logical",
        "Funny",
        "Kind",
    ],
  },
  {
    id: 8,
    values: [
        "Inquisitive",
        "Responsible",
        "Thoughtful",
        "Assertive",
        "Thorough",
        "Careful",
        "Confident",
        "Leader",
        "Dreamer",
        "Caring",
        "Quick",
    ],
  },
  {
    id: 9,
    values: [
        "Communicator",
        "Determined",
        "Persistent",
        "Easy going",
        "Accurate",
        "Positive",
        "Aware",
        "Courageous",
        "Flexible",
        "Listener",
        "Patient",
    ],
  },
  
];


